[phases.setup]
aptPkgs = ["openjdk-17-jdk"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "java -jar target/chat2db-server-1.0.0.jar"
